<?php

$GLOBALS['params'] = array("BandcampBridge" => array("tag" => "test"),
		    "CpasbienBridge" => array("q" => "test"),
		    "CryptomeBridge" => array("n" => "5"),
		    "BooruprojectBridge" => array("i" => "shadowcrest.booru.org", "p" => "post", "t" => "cats"),
		    "DanbooruBridge" => array("p" => "popular", "t" => "test"),
		    "DauphineLibereBridge" => array("u" => "france-monde"),
		    "DailymotionBridge" => array(array("u" => "test"), array("p" => "x3w8ri_knamhawall_pyaar-ki-yeh-ek-kahani-1st-playlist"), array("s" => "test", "pa" => "1")),
		    "DollbooruBridge" => array("p" => "3"),
		    "DuckDuckGoBridge" => array("u" => "test"),
		    "EZTVBridge" => array("i" => "1253"),
		    "FacebookBridge" => array("u" => "Numerama"),
		    "FourchanBridge" => array("t" => "https://boards.4chan.org/b/thread/638605020"),
		    "FlickrTagBridge" => array(array("u" => "7326810@N08"), array("q" => "photo")),
		    "Freenews" => array("id" => ""),
		    "Gawker" => array("site" => "lifehacker"),
		    "GelbooruBridge" => array("p" => "1", "t" => "test"),
		    "GiphyBridge" => array(array("s" => "test"), array("s" => "test", "n" => "12")),
		    "GooglePlusPostBridge" => array("username" => "+LinusTorvalds"),
		    "GoogleSearchBridge" => array("q" => "test"),
		    "HDWallpapersBridge" => array("c" => "anime", "m" => "5", "r" => "1920x1200"),
		    "IdenticaBridge" => array("u" => "bobjonkman"),
		    "InstagramBridge" => array("u" => "korben00"),
		    "KonachanBridge" => array("p" => "1", "t" => "hatsune_miku"),
		    "LeBonCoinBridge" => array("r" => "nord_pas_de_calais", "k" => "meuble"),
		    "LolibooruBridge" => array("p" => "1", "t" => "long_image"),
		    "MilbooruBridge" => array("p" => "1", "t" => "photo"),
		    "MspabooruBridge" => array("p" => "1", "t" => "blood"),
		    "OpenClassroomsBridge" => array("u" => "informatique"),
		    "ParuVenduImmoBridge" => array("minarea" => "1", "maxprice" => "10000000", "pa" => "FR", "lo" => "62"),
		    "PickyWallpapersBridge" => array("c" => "anime", "s" => "other", "m" => "10", "r" => "1920x1200"),
		    "PinterestBridge" => array(array("u" => "petersom", "b" => "peter-som-spring-2014"), array("q" => "photo")),
		    "Rule34Bridge" => array("p" => "1", "t" => "photo"),
		    "Rule34pahealBridge" => array("p" => "1"),
		    "SafebooruBridge" => array("p" => "1", "t" => "photo"),
		    "SakugabooruBridge" => array("p" => "1", "t" => "various_artists"),
		    "ScoopItBridge" => array("u" => "test"),
		    "SuperbWallpapersBridge" => array("c" => "anime", "m" => "10", "r" => "1920x1200"),
		    "SoundcloudBridge" => array("u" => "futureisnow"),
		    "TagBoardBridge" => array("u" => "test"),
		    "TbibBridge" => array("p" => "1", "t" => "test"),
		    "ThePirateBayBridge" => array("q" => "test"),
		    "TwitchApiBridge" => array(array("channel" => "cdv_nesblog", "broadcasts" => "true"), array("channel" => "cdv_nesblog", "broadcasts" => "true", "limit" => "5")),
		    "TwitterBridge" => array(array("q" => "test"), array("u" => "Mitsukarenai")),
		    "TwitterBridgeClean" => array(array("q" => "test"), array("u" => "Mitsukarenai")),
		    "TwitterBridgeExtended" => array(array("q" => "test"), array("u" => "Mitsukarenai")),
 		    "TwitterBridgeTweaked" => array(array("q" => "test"), array("u" => "Mitsukarenai")),
            "UnsplashBridge" => array("m" => "10", "w" => "1920", "q" => "100"),
		    "WallpaperStopBridge" => array("c" => "animal-wallpaper", "s" => "bear-wallpaper", "m" => "10", "r" => "1920x1200"),
		    "WhydBridge" => array("u" => "u/530642f37e91c862b2b5aa57"),
		    "WordPressBridge" => array("url" => "https://odieuxconnard.wordpress.com", "name" => "test"),
		    "WorldOfTanks" => array("lang" => "en", "category" => "18"),
		    "XbooruBridge" => array("p" => "1", "t" => "photo"),
		    "YandereBridge" => array("p" => "1", "t" => "photo"),
		    "YoutubeBridge" => array(array("u" => "epenser1"), array("c" => "UCHnyfMqiRRG1u-2MsSQLbXA"), array("p" => "PLGPWPtcc-r80AIhTGU5oAbsruqBCtv9JU"), array("s" => "test"))
);

